# Generated by Django 5.1.6 on 2025-02-28 14:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0006_leaderboard_lungs'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Leaderboard',
            new_name='Leaderboard_heart',
        ),
    ]
